---
# tasks file for byd_ops
# byd_ops追加
- name: user_add
  user:
    name: byd_ops
    groups: wheel
    password: "{{ byd_pass | password_hash('sha512') }}"
    generate_ssh_key: yes
    uid: 1500

- name: rename id_rsa.pub -> authorized_keys
  shell: "mv ~byd_ops/.ssh/{id_rsa.pub,authorized_keys}"
  args:
    creates: "~byd_ops/.ssh/authorized_keys"

- name: download ssh-key
  fetch:
    src: "~byd_ops/.ssh/id_rsa"
    dest: "{{ pkey_dir | default('/var/tmp', true) }}/{{ ansible_nodename }}/byd_ops.pem"
    flat: yes

#- name: mkdir_ssh
#  file:
#    path: /home/byd_ops/.ssh
#    state: directory
#    owner: byd_ops
#    group: byd_ops
#    mode: 0700

#- name: user_sshkey
#  copy:
#    src: ../../../key/byd_ops.pem.pub
#    dest: /home/byd_ops/.ssh/authorized_keys
#    owner: byd_ops
#    group: byd_ops
#    mode: 0600

- name: sudoers_add
  template:
    src: ../templates/byd_ops.j2
    dest: /etc/sudoers.d/byd_ops
    owner: root
    group: root
    mode: 0600
